### PR TITLE
Updated to use the latest Vaadin version (7.4.2)

### PR DESCRIPTION
**Pull request by skogdoom**
Hi!

I needed to make sure that this addon still worked with later versions of vaadin, so I decided to update it...

I didn't manage to build it properly with gradle, so I took the liberty of switching back to maven again.

While I was at it I also performed some minor cleanup of the jsp, changed the java version to 1.6 (since that is what vaadin supports), upgraded the jetty version and replaced the web.xml with a servlet.

Br,
/David

### CODE REVIEW

**Comment by gpedro** [comment]
@ripla can you merge and publish?

**Comment by ripla** [comment]
Hi, thanks for the contribution @skogdoom!

 * I think I'll keep the Gradle build for now
 * The add-on should already work for the latest Vaadin
 * The JSP fix looks nice, my JSP is a little rusty so help is appreciated!

**Comment by gpedro** [comment]
@ripla when you'll upload to central?

**Comment by ripla** [comment]
@gpedro I just tested and the current version seems to work with the newest version of Vaadin just fine. The changes between 2.1 and master are mainly just renaming the packages and tweaking the build. If you have any problems with the current version in the Directory, please [create a new issue](https://github.com/ripla/Formsender/issues/new).

**Pull request closed without merging**
